### ISSUE TITLE
clicking within simulations item table in simulations editor when the table is empty produces an error

### ISSUE THREAD

**Issue by feigelman** [gQSPSim/gQSPSim_public#11]
clicked the table with no rows and get the following 

Index exceeds the number of array elements. Index must not exceed 0.

Error in QSPViewerNew.Application.SimulationPane/onTableSelectionChange (line 418)
            obj.SelectedRow = Indices(1);

Error in QSPViewerNew.Application.SimulationPane>@(h,e)obj.onTableSelectionChange(e) (line 270)
            obj.SimItemsTable.CellSelectionCallback = @(h,e) obj.onTableSelectionChange(e);
 
418             obj.SelectedRow = Indices(1);

**Comment by simkaryote** [comment]
This was a latent bug in the code before the refactor.
