### ISSUE TITLE
"Simulation items" label on simulations item editor appears incorrectly

### ISSUE THREAD

**Issue by feigelman** [gQSPSim/gQSPSim_public#12]
shows "Simulation It...", running on a mac 2022b

**Comment by simkaryote** [comment]
I don't know what this means. Please clarify, maybe a screenshot?

**Comment by feigelman** [comment]
![image](https://user-images.githubusercontent.com/3785793/208701783-c09760b9-d1f4-48f7-b65d-4a6a3a47f252.png)

**Comment by simkaryote** [comment]
Fixed. In general there are layout issues left to address. Adding an issue for that.
