### ISSUE TITLE
Creating new items through the context menu produces error

### ISSUE THREAD

**Issue by feigelman** [gQSPSim/gQSPSim_public#5]
Adding items of any type through the context menu produces an error:

Error using type
Too many output arguments.

Error in QSPViewerNew.Application.MainView>@(h,e)obj.onMenuNotifyAdd(type) (line 458)
            uimenu(obj.contextMenuStore.header, "Text", "Add new", "MenuSelectedFcn", @(h,e)obj.onMenuNotifyAdd(type));

**Comment by simkaryote** [comment]
Justin - I don't see this and there is a test for it that runs at MathWorks. 
Before you make a bunch of issues could you make sure you have the HEAD of the update_old_dev branch.

Thanks.

**Comment by feigelman** [comment]
I have the latest version ec4593aa72ff44666c5998125743cef16b50b6bc following our email exchange and I still see this issue. I see that the function signature is clearly wrong (type is not defined!) so seems to be a bug indeed.

**Comment by simkaryote** [comment]
I see the issue. I had some changes that I did not put into the repo. I will push those shortly.

**Comment by simkaryote** [comment]
Fixed with c28bc105a97d9a1aa531e3080626ceb7e0aa7446
