### ISSUE TITLE
error when selecting task cell in simulation "Simulation Items" table

### ISSUE THREAD

**Issue by feigelman** [gQSPSim/gQSPSim_public#8]
created a new row in the table, selected the Task cell, got the following error:

Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Interrupt while evaluating Button PrivateButtonPushedFcn.

No public property 'UIFigure' for class 'MainView'.

Error in QSPViewerNew.Application.ViewPane/getSelectionNode (line 1300)
            position = obj.ParentApp.OuterShell.UIFigure.Position;

Error in QSPViewerNew.Application.SimulationPane/onTableSelectionChange (line 426)
                    selectedTaskNode = obj.getSelectionNode("Task");

Error in QSPViewerNew.Application.SimulationPane>@(h,e)obj.onTableSelectionChange(e) (line 270)
            obj.SimItemsTable.CellSelectionCallback = @(h,e) obj.onTableSelectionChange(e);

**Comment by feigelman** [comment]
seems to be the case for any cell in that table

**Comment by simkaryote** [comment]
Fixed. 
Pushing now.

**Comment by simkaryote** [comment]
Closing this. Feel free to reopen if you still see it.
